### PR TITLE
Add Linux support with nmcli.

### PR DESCRIPTION
**Pull request by fcapovilla**
Fixes issues #2.

### CODE REVIEW

**Comment by Pedneri1** [comment]
Thanks for your contribution, but I'm having troubles when running on Ubuntu 16.04 from an USB WiFi adapter.

When I run `WifiPassword.get("mySSID")` I get the error

```
Error: Option '-get-values' is unknown, try 'nmcli -help'.
     ** (CaseClauseError) no case clause matching: {"", 2}
    (wifi_password 0.1.0) lib/wifi_password.ex:39: WifiPassword.get/1
```

Tried to remove the `--get-values` flag but got this other error:

```
Error: Object '802-11-wireless-security.psk,802-11-wireless-security.wep-key0' is unknown, try 'nmcli help'.
```

Taking a look at [this library](https://github.com/kevva/wifi-password) I saw that their [Linux approach](https://github.com/kevva/wifi-password/blob/master/lib/linux.js) used the following command:

`cat /etc/NetworkManager/system-connections/{ssid}`

What do you think? Any thoughts?

**Comment by fcapovilla** [comment]
I think Ubuntu 16.04 has an older version of NetworkManager, and the `--get-values` parameter doesn't exist on that version.
According to the nmcli manpage (https://www.mankier.com/1/nmcli#--get-values), `--get-values` is just a shortcut for `--mode tabular --terse --fields`, so I updated my pull request to use the full version of the command.
I'll try to get an Ubuntu VM to do more testing.

I saw the Linux approach on `kevva/wifi-password`, but the `cat` method seemed to cause issues in some situations (Looking at their issues), so I went with the `nmcli` method. This method seems safer to me, as long as the parameters are supported on all versions of nmcli.

Also, I currently use Fedora, and my `/etc/NetworkManager/system-connections/` empty, so I'm guessing my wifi configurations are somewhere else on my system. `nmcli` works on Fedora, so it might work on more systems than the `cat` method.

**Comment by Pedneri1** [comment]
Just tested your new code and it's working now, but there is a little remaining problem.

When running 

`WifiPassword.get("my-ssid")` 

this is returned: 

`{:ok, "mysecretpass--"}`

The last two characters `--` are (100% sure) not part of my password.

Any thoughts?

########### Edit

Figured ot that when running

`nmcli --show-secrets --mode tabular --terse --fields 802-11-wireless-security.psk,802-11-wireless-security.wep-key0 connection show id my-ssid`

The response has a breakline and the two dashes. So I'm guessing here that it's a matter of sanitizing the string

**Comment by fcapovilla** [comment]
It seems Ubuntu's version of nmcli adds `--` to the output when a value is empty. I don't have this problem on Fedora.
The query asks for WPA2 and WEP passwords, so if the connection uses WPA2 the `--` you see must be the empty value for WEP.

I'll try to sanitize the string without causing problems if the password is really `--`.

**Comment by fcapovilla** [comment]
`--` doesn't seem to be a valid Wifi password, so I guess I can safely remove lines containing only `--` in the nmcli output.
I pushed another fix, but I was unable to run an Ubuntu 16.04 VM with working wifi to test it.
Can you check if this version works on Ubuntu?

**Comment by Pedneri1** [comment]
Works like a charm. Thanks! Great job

**Comment by fcapovilla** [comment]
Can you add the "hacktoberfest-accepted" label to this pull request, so it's counted for Hacktoberfest?
Thanks!

**Pull request merged**
